# syracuseSequence.py
# A program that prints a Syracuse sequence.
"""The Syracuse (also called "Collatz" or "Hailstone") sequence is generated by
starting with a natural number and repeatedly applying the following function
until reaching 1:
    syr(x) = x/2 (if x is even), 3x + 1 (if x is odd)
For example, the Syracuse sequence starting with 5 is: 5, 16, 8, 4, 2, 1. It is
an open question in mathematics whether this sequence will always go to 1 for 
every possible starting value.

Write a program that gets a starting value from the user and then prints the
Syracuse sequence for that starting value."""

def userInput():
    try:
        while True:
            val = int(input("Please enter a positive whole number to start \
the sequence: "))
            if val > 0:
                break
    except (SyntaxError, NameError, TypeError, ValueError) as err:
        print("You have to enter a positive whole number to start the \
sequence. Exiting.")
        print(err.args)
        quit(0)
    return val

def main():
	
    print("This program prints a Syracuse sequence.")
    
    val = userInput()
                
    while val != 1:
        print(val)
        if val % 2 == 1:
            val = 3 * val + 1
        else:
            val = val // 2
    print(val)    
main()
